# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages

r: bioc-devel

branches:
  only:
    - master

before_script:
  - Rscript -e 'install.packages(c("rmarkdown", "knitr", "covr"))'
  - Rscript -e 'BiocManager::install("BiocStyle")'
after_success:
  - Rscript -e 'covr::codecov()'
